### ISSUE TITLE
No create.handlers method found for custom runtime plugin 'typescript' (architect/plugin-typescript)

### ISSUE THREAD

**Issue by Donato-EF** [architect/plugin-typescript#15]
Hi, I am getting this error when running `arc init` with new http endpoints.

```
Version ⌁ Architect 10.14.2
         cwd ⌁ /XXX

✓ Create Existing Architect project manifest found
init failed! No create.handlers method found for custom runtime plugin 'typescript' (architect/plugin-typescript)
ReferenceError: No create.handlers method found for custom runtime plugin 'typescript' (architect/plugin-typescript)
    at writeCode (/XXX/node_modules/@architect/create/src/write-functions/write-code.js:40:15)
    at writeFunctions (/XXX/node_modules/@architect/create/src/write-functions/index.js:18:13)
    at create (/XXX/node_modules/@architect/create/src/index.js:100:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/XXX/node_modules/@architect/architect/src/index.js:78:7)
    at async /XXX/node_modules/@architect/architect/src/index.js:94:5
```

**Comment by ryanblock** [comment]
Please see: https://github.com/architect/architect/issues/1410

Sorry, not sure why I never merged this. Doing that now!
